spring:
   profiles:
     active: default

spring.jmx:
   enabled: false

spring.datasource:
   driverClassName: org.h2.Driver
   url: jdbc:h2:mem:greenpool;MODE=MySQL

server:
  port: 8080
  contextPath: /greenpool/

security:
   basic:
      enabled: false

spring.jpa:
    hibernate.ddl-auto: create-drop
